"""empty message

Revision ID: 1963c6e7321c
Revises: e23b7abe7e19
Create Date: 2019-11-15 17:15:08.269357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1963c6e7321c'
down_revision = 'e23b7abe7e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=40), nullable=True),
    sa.Column('type', sa.String(length=60), nullable=True),
    sa.Column('begin_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Integer(), nullable=True),
    sa.Column('major', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_add_time'), 'mission', ['add_time'], unique=False)
    op.add_column('user', sa.Column('can_add', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('is_check', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('is_input', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('view_log', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'view_log')
    op.drop_column('user', 'is_input')
    op.drop_column('user', 'is_check')
    op.drop_column('user', 'can_add')
    op.drop_index(op.f('ix_mission_add_time'), table_name='mission')
    op.drop_table('mission')
    # ### end Alembic commands ###
