"""empty message

Revision ID: 369c3de4710f
Revises: 5ee90398e4ff
Create Date: 2019-11-29 14:56:03.980160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '369c3de4710f'
down_revision = '5ee90398e4ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('majorlist', sa.Column('majorlist_code', sa.Integer(), nullable=True))
    op.drop_column('majorlist', 'code_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('majorlist', sa.Column('code_list', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('majorlist', 'majorlist_code')
    # ### end Alembic commands ###
