"""empty message

Revision ID: 5ee90398e4ff
Revises: a92aa61d760b
Create Date: 2019-11-29 14:54:46.737740

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ee90398e4ff'
down_revision = 'a92aa61d760b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('majorlist', sa.Column('code_list', sa.Integer(), nullable=True))
    op.drop_column('majorlist', 'code_majorlist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('majorlist', sa.Column('code_majorlist', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('majorlist', 'code_list')
    # ### end Alembic commands ###
