"""empty message

Revision ID: 9511433bf073
Revises: bae965350e7a
Create Date: 2019-12-06 15:24:51.104856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9511433bf073'
down_revision = 'bae965350e7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('reason', sa.String(length=600), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log', 'reason')
    # ### end Alembic commands ###
