"""empty message

Revision ID: a92aa61d760b
Revises: 1963c6e7321c
Create Date: 2019-11-29 14:38:54.486678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a92aa61d760b'
down_revision = '1963c6e7321c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('majorlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_majorlist', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('majorlist')
    # ### end Alembic commands ###
