"""empty message

Revision ID: add0cd369c57
Revises: 369c3de4710f
Create Date: 2019-11-29 14:56:35.357748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add0cd369c57'
down_revision = '369c3de4710f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('majorlist', sa.Column('majorlist_name', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('majorlist', 'majorlist_name')
    # ### end Alembic commands ###
