"""empty message

Revision ID: bae965350e7a
Revises: add0cd369c57
Create Date: 2019-11-29 14:57:07.260426

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bae965350e7a'
down_revision = 'add0cd369c57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('majorlist', sa.Column('code_majorlist', sa.Integer(), nullable=True))
    op.add_column('majorlist', sa.Column('name_majorlist', sa.String(length=60), nullable=True))
    op.drop_column('majorlist', 'majorlist_name')
    op.drop_column('majorlist', 'majorlist_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('majorlist', sa.Column('majorlist_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('majorlist', sa.Column('majorlist_name', mysql.VARCHAR(length=60), nullable=True))
    op.drop_column('majorlist', 'name_majorlist')
    op.drop_column('majorlist', 'code_majorlist')
    # ### end Alembic commands ###
